version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      angular:
        patterns:
          - '@angular/*'
          - '@angular-devkit/*'
  - package-ecosystem: "npm"
    directory: "/src"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      capacitor:
        patterns:
          - '@capacitor/*'
          - 'capacitor-secure-storage-plugin'
