dist: bionic
os:
  - linux
services:
  - docker
  - xvfb
language: node_js
node_js:
  - "12.16.1"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
# Install Chrome
addons:
  apt:
    packages:
      - dpkg
  chrome: stable
before_install:
  - npm i -g @angular-devkit/schematics-cli@0.803.25 @angular/cli @vue/cli @ionic/cli codecov react-native-cli
install:
  - npm ci
script:
  - set -e
  - npm run build
  - npm test && npm run coverage
  # create apps and confirm tests still pass
  - ./test-all.sh
after_success:
  - codecov
notifications:
  webhooks:
    on_success: always
    on_failure: always
    on_start: never
