name: Schematics

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]') && !contains(github.event.ref_type, '[tag]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - name: Install Schematics Utilities snapshot
        run: |
          git clone -b angular10 https://github.com/mraible/schematics-utilities.git
          cd schematics-utilities && npm link
          cd .. && npm link schematics-utilities
      - run: npm i -g codecov
      - run: npm test
      - run: npm run coverage
      - uses: codecov/codecov-action@v1

